### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by IslamOmar-360Imaging** [MoustaphaSaad/mn#68]
At [ref](https://github.com/MoustaphaSaad/mn#buf)
`mn::buf_remove_`**of**`(numbers, [](auto n){ return n % 2 == 0; });` ==> `mn::buf_remove_if(numbers,...`

**Comment by MoustaphaSaad** [comment]
fixed in a93a428bcceb723b4b1b157988401a184d03d1a0
