### ISSUE TITLE
Add Gc_Str, Gc_Buf, ...

### ISSUE THREAD

**Issue by IslamOmar-360Imaging** [MoustaphaSaad/mn#70]
As I understand you allow using mn_defer which wraps types into a struct with a destructor, so I think it would be acceptable to add a struct which inherits from main types and provide a destructor for them.

Ex: 
```C++
struct Gc_Str : Str
{
	~Gc_Str()
	{
		str_free(*self);
	}
};
```
Or `Destructable_Str` , ...

I think that slicing problem won't affect the result as the argument is taken by reference `Str&`.

Another question:
Does memory::tmp() allocator needs manual free with `mn::memory::tmp()->free_all()`? When is it called?

**Comment by MoustaphaSaad** [comment]
1. If you need to free the string at the end of the scope just allocate it using tmp allocator, and just don't write free for it
2. yes, each application knows the perfect spot to free its tmp allocator, for example in case of a game it'll be after each frame, web server will be after each request, etc...

let me know if this resolves your issue so that i can close it

**Comment by IslamOmar-360Imaging** [comment]
Just to be sure `mn_defer` is equivalent to `mn::memory::tmp()` for all types.

**Comment by MoustaphaSaad** [comment]
it's not equivalent, they are both completely different constructs, but in general if you need some tmp memory for the duration of this function you should use tmp allocator, defer is used in other cases like file close, or mutex unlock, etc...

**Comment by IslamOmar-360Imaging** [comment]
If I want to close my file after scope end, I have to use `mn_defer`, right?, but why is OK with `mn::Str`?

**Comment by IslamOmar-360Imaging** [comment]
OK, I got it.

**Comment by IslamOmar-360Imaging** [comment]
@MoustaphaSaad I think that when I have a `for` loop using `str_tmp` won't be efficient, so force free at the end of the scope is more safe.

**Comment by MoustaphaSaadSymbyo** [comment]
@IslamOmar-360Imaging how about moving the allocation outside of the loop?, RAII won't be efficient either way, you'll have to go through global system allocator each loop, so don't do that, RAII or not
