### ISSUE TITLE
Assert macros inconsistent expansion

### ISSUE THREAD

**Issue by mahrr** [MoustaphaSaad/mn#75]
Currently `mn_assert` and `mn_assert_msg` would compile in debug mode without a statement-trailing semicolon, since they are expanded into a block statement `{ if (expr) { ... } else { ... } }`, but they won't compile in a non-debug mode, since they are expanded into an expression `((void)0)`, which would fail to compile without the trailing semicolon, if it's used as an expression statement (this is mostly the case with asserts). 

#### Suggestion

They could be expanded into a do-while statement, such as the following:

```C++
#define mn_assert(expr) \
   do { if (expr) {} else { mn::_report_assert_message(#expr, nullptr, __FILE__, __LINE__); mn_debug_break(); } } while (false)
```

this is not a valid syntax without its trailing semicolon.

Or they could be expanded into a short-circuited or expression, or a conditional expression, such as the following:

```C++
#define mn_assert(expr) \
  ( (expr) ? ((void)0) : (mn::_report_assert_message(#expr, nullptr, __FILE__, __LINE__), mn_debug_break(), (void)0) )
```

I prefer the first approach, as it enforces asserts to be only used as statements. If the first approach is used, I think the expansion of non-debug mode should also be a statement, maybe an empty do-while.

**Comment by MoustaphaSaad** [comment]
fixed [here](https://github.com/MoustaphaSaad/mn/commit/7371f0f18f31e5fdda31476a9328ce092006dd54)
